# Generated by Django 5.0.3 on 2024-03-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
