# Generated by Django 5.0.3 on 2024-03-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0005_rename_streak_leaderboard_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.AddField(
            model_name='workout',
            name='newactivity',
            field=models.CharField(default='', max_length=70),
        ),
    ]
