# Generated by Django 5.0.3 on 2024-03-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0006_remove_workout_activity_remove_workout_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
