# Generated by Django 5.0.3 on 2024-03-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0007_alter_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
    ]
